user := env("DOCKERHUB_USER", "akhilfolium")
docker := env("DOCKER", if path_exists("/usr/bin/podman") == "true" { "podman" } else { "docker" })

# Build image
build:
    {{docker}} build -t {{user}}/hackernews .

# Push image
push:
    {{docker}} push {{user}}/hackernews

# Build + push
release: build push
