user := env("DOCKERHUB_USER", "akhilfolium")
docker := env("DOCKER", if path_exists("/usr/bin/podman") == "true" { "podman" } else { "docker" })

build:
    {{docker}} build -t {{user}}/legal-agent .

push:
    {{docker}} push {{user}}/legal-agent

release: build push
