services:
  langgraph:
    build: .
    container_name: langgraph
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "10000:10000"
    networks:
      - agents-net

networks:
  agents-net:
    external: true
