//! The LLM tool surface — the read-only GitHub operations exposed to the model.
//!
//! Each tool is a thin `#[rig_tool]` wrapper over [`crate::github`]: rig generates the `Tool`
//! impl, the JSON Schema (from the function signature + doc comments), and the argument struct,
//! and the body just delegates to the GitHub client. `build_tools` assembles them into the
//! `ToolSet` + `ToolDefinition`s the agent hands the LLM.

use rig::completion::ToolDefinition;
use rig::tool::{ToolDyn, ToolSet};
use rig::tool_macro as rig_tool;

use crate::github;

/// Builds every tool and its rig `ToolDefinition`. The tool structs (`ListCommits`, …) are
/// generated by `#[rig_tool]` on the functions below. Read this first for the complete tool
/// inventory the agent can call.
pub fn build_tools() -> (ToolSet, Vec<ToolDefinition>) {
    let mut builder = ToolSet::builder();
    let mut defs = Vec::new();

    macro_rules! register {
        ($tool:expr) => {{
            let tool = $tool;
            defs.push(definition_of(&tool));
            builder = builder.static_tool(tool);
        }};
    }

    register!(ListCommits);
    register!(CompareDiff);
    register!(SearchPrs);
    register!(GetCommit);
    register!(ReadFile);
    register!(FindReferences);

    (builder.build(), defs)
}

#[rig_tool(
    description = "List commits since a given time to the default branch of one or \
    more GitHub repos. Returns hash, message, author, date, and url for each commit, newest \
    first, in one section per repo."
)]
pub async fn list_commits(
    /// One or more repos in "owner/name" format, e.g. ["Nasiko-Labs/nasiko-cloud-rs"]. Pass
    /// several entries to cover multiple repos in a single call.
    repos: Vec<String>,
    /// ISO-8601 timestamp; only commits after this time are returned.
    since: String,
) -> Result<String, GitHubToolError> {
    Ok(github::list_commits(&repos, &since).await)
}

#[rig_tool(
    description = "Get the aggregated file-level diff (files changed, added/removed \
    lines, and patches) covering every commit since a given time, for one or more repos. Call \
    this after list_commits, and only for repos where it found at least one commit."
)]
pub async fn compare_diff(
    /// One or more repos in "owner/name" format, matching what was passed to list_commits.
    repos: Vec<String>,
    /// Same ISO-8601 timestamp passed to list_commits.
    since: String,
) -> Result<String, GitHubToolError> {
    Ok(github::compare_diff(&repos, &since).await)
}

#[rig_tool(
    description = "Search for pull requests with activity (opened, merged, or closed) \
    since a given time, across one or more repos. Returns number, title, state, and the \
    created/merged/closed timestamps for each, so you can classify them yourself relative to \
    the window."
)]
pub async fn search_prs(
    /// One or more repos in "owner/name" format.
    repos: Vec<String>,
    /// ISO-8601 timestamp.
    since: String,
) -> Result<String, GitHubToolError> {
    Ok(github::search_prs(&repos, &since).await)
}

#[rig_tool(
    description = "Read one specific commit in a GitHub repo: its message, author, \
    date, parent_hash, and the list of changed files (status + line counts + per-file patch), \
    most-changed first. Omit `commit_hash` to get the latest commit on the default branch. Use \
    the returned parent_hash with read_file to fetch the BEFORE version of a changed file."
)]
pub async fn get_commit(
    /// A single repo in "owner/name" format, e.g. "Nasiko-Labs/nasiko-cloud-rs".
    repo: String,
    /// Commit hash to inspect. Omit or leave empty for the latest commit on the default branch.
    commit_hash: Option<String>,
) -> Result<String, GitHubToolError> {
    github::get_commit(&repo, commit_hash.as_deref())
        .await
        .map_err(GitHubToolError)
}

#[rig_tool(
    description = "Read the FULL contents of one file in a GitHub repo at a specific git \
    ref (commit hash, branch, or tag). Use this to read a changed file's exact before/after: \
    pass the commit hash for the new version and the commit's parent_hash for the old version. \
    Prefer this over the truncated patch when you need real line-by-line context."
)]
pub async fn read_file(
    /// A single repo in "owner/name" format.
    repo: String,
    /// File path within the repo, e.g. "oss/auth/src/lib.rs".
    path: String,
    /// Git ref to read at: a commit hash (use parent_hash for the BEFORE version), branch, or tag.
    git_ref: String,
) -> Result<String, GitHubToolError> {
    github::read_file(&repo, &path, &git_ref)
        .await
        .map_err(GitHubToolError)
}

#[rig_tool(
    description = "Find files in a GitHub repo that reference a symbol (function, type, \
    constant name). Use this to ground an impacted-files list: for a changed symbol, this returns \
    the files that mention it. Matches are TEXTUAL (default branch only) so verify each is a real \
    dependency rather than a name collision."
)]
pub async fn find_references(
    /// A single repo in "owner/name" format.
    repo: String,
    /// The symbol to search for (e.g. a function or type name).
    symbol: String,
) -> Result<String, GitHubToolError> {
    github::find_references(&repo, &symbol)
        .await
        .map_err(GitHubToolError)
}

// ─── Supporting infrastructure ────────────────────────────────────────────────

/// Error surfaced to rig when a tool fails. The GitHub client speaks plain `String`s; this
/// wraps them so the tool signatures satisfy `Tool::Error: std::error::Error`.
#[derive(Debug, thiserror::Error)]
#[error("{0}")]
pub struct GitHubToolError(String);

/// Builds a `ToolDefinition` (name/description/schema) from a tool's rig metadata.
fn definition_of(tool: &dyn ToolDyn) -> ToolDefinition {
    ToolDefinition {
        name: tool.name(),
        description: tool.description(),
        parameters: tool.parameters(),
    }
}
